language: minimal

sudo: required

services:
  - docker

script:
  - ./travis.sh

deploy:
  provider: releases
  api_key: "$GITHUB_API_TOKEN"
  file: "raspbian-setup-$TRAVIS_TAG.zip"
  skip_cleanup: true
  on:
    tags: true